{% set name = "fps-file-id" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_file_id-{{ version }}.tar.gz
  sha256: fc1f65b43b036a5a4f5fb920a626b90f5a5599cf68bf3b5e101887cbd7796cda

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.11.2,<0.12.0
    - anyio >=3.6.2,<5
    - sqlite-anyio >=0.2.0,<0.3.0

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_file_id

about:
  home: https://github.com/jupyter-server/jupyverse/plugins/file_id
  summary: An FPS plugin for the file ID API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/plugins/file_id
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
